### ISSUE TITLE
No usable version of the libssl was found

### ISSUE THREAD

**Issue by jimsgreen** [dsavell/docker-azp-agent#15]
How do you resolve this error in 20.04? 

1. Determining matching Azure Pipelines agent...
2. Downloading and installing Azure Pipelines agent...
3. Configuring Azure Pipelines agent...

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /azp/agent/externals/tee/license.html

>> Connect:

No usable version of the libssl was found
./config.sh: line 86:    67 Aborted                 (core dumped) ./bin/Agent.Listener configure "$@"

**Comment by dsavell** [comment]
Hey,

Thanks, I have updated my 20.04 Dockerfile with latest changes was missing the libssl1.0, they must have updated there upstream requirements.

Regards,
